import "./css/globals.css";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import NavBar from "./NavBar";
import { Container, Theme } from "@radix-ui/themes";
import AuthProvider from "./auth/AuthProvider";
import QueryClientProvider from "./QueryClientProvider";

const roboto = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      {/* Provider OAuth Context */}
      <QueryClientProvider>
        <AuthProvider>
          <body className={roboto.variable}>
            <Theme>
              <NavBar />
              <main className="p-5">
                {/* Container constrains the maximum width of page content. Set size to 1,2,3 or 4 */}
                <Container>{children}</Container>
              </main>
            </Theme>
          </body>
        </AuthProvider>
      </QueryClientProvider>
    </html>
  );
}
