import "./css/globals.css";
import type { Metadata } from "next";
import { Roboto_Mono } from "next/font/google";
import NavBar from "./NavBar";
import { Theme } from "@radix-ui/themes";

const roboto = Roboto_Mono({
  subsets: ["latin"],
  variable: "--font-roboto",
  weight: ["100", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={roboto.variable}>
        <Theme>
          <NavBar />
          <main className="p-5">{children}</main>
        </Theme>
      </body>
    </html>
  );
}
